# example configuration for couning rate on GPIO pins

DAQModule: GPIOCount

GPIOpins: [20, 21] # GPIO pin numbers
#GPIOpins:   [21]   # GPIO pin numbers
Modes:      [0, 0] # 0:rising, 1:falling edge

