# example of a configuration file for PicoScope 2000 Series

DAQModule: PSConfig         

PSmodel: 2000a
# channel configuration 
picoChannels: [A, B]
ChanRanges: [2., 2.]
ChanOffsets: [-1.95, -1.95]
ChanModes: [DC, DC]
sampleTime: 2.0E-02
Nsamples: 100

# trigger
trgActive: false  # true to activate
trgChan: A
#trgThr: 0.1
#pretrig: 0.05
#trgTyp: Rising
#trgTO: 1000  # time-out

# signal generator 
# frqSG: 100.E+3 # put 0. do disable
frqSG: 0. 

