# example of a configuration file for ADC ADS1115

NChannels:  1           # number of Channels
ADCChannels: [0, 1]     # chosen ADC-Channels (possibel values: 0, 1, 2, 3)
ConvFactors: [1., 1.]   # conversion factors for calculation of sensor values
Gain: [2/3, 1]            # programmable gain of ADC-Channel
                          # possible values for Gain:
                          #  - 2/3 = +/-6.144V
                          #  -   1 = +/-4.096V
                          #  -   2 = +/-2.048V  
                          #  -   4 = +/-1.024V
                          #  -   8 = +/-0.512V
                          #  -  16 = +/-0.256V
sampleRate: 860        # programmable Sample Rate of ADS1115
                          # possible values for SampleRate: 
                          # 8, 16, 32, 64, 128, 250, 475, 860