# example config for INA219 current sensor

DAQModule: INA219Config

NChannels: 2  # 1: only current 2: current and voltage; 3: current, voltage and power
maxAmp: 0.5  # current range in A, max. 3.1999 
maxVolt: 16. # alternative: 32.
