# example of a configuration file for ADC MCP3008

DAQModule: MCP3008Config

ADCChannels:   [0, 1, 2, 3]   # active Channels (0 - 7)

DifModeChan:  [false, false, false, false ] # differential mode for channels 0/1, 2/3, 4/5 or 6/7
#             0:    0 - 1     1: 1-0    2: 2-3   3:3-2  4: 4-5  5:5-4  6: 6-7  7: 7-6

VRef:       5.0   # Reference Voltage

NBits:      10    # ACD resolution in Bits

