# example of a configuration file for PicoScope 2000 Series

DAQModule: PSConfig         

#PSmodel: '2000' # PS model 220xA
PSmodel: '2000a' # PS model 2x0xB

# channel configuration 
picoChannels: [A, B]
ChanRanges: [2., 2.]
ChanOffsets: [-1.95, -1.95] # not for PS model 2204A
ChanModes: [DC, DC]
sampleTime: 2.0E-02
Nsamples: 200

# trigger
trgActive: false  # true to activate
trgChan: A
#trgThr: 0.0
#pretrig: 0.05
#trgTyp: Rising
trgTO: 4  # set short time-out for PS model 2204A

# signal generator 
# frqSG: 100.E+3 # put 0. do disable
frqSG: 0. 

